In [1]:
import matplotlib.pyplot as plt

In [4]:
from LSQClassifier import LSQClassifier
from data_utils import get_train_test

X_train, X_test, y_train, y_test = get_train_test(k=20)

# model = LSQClassifier(solver='lm')
model = LSQClassifier(solver='gauss')
# model = LSQClassifier(solver='sgd',solverkwargs={'TOL' : 1e-3,'ITER_MAX' : 600,'batch_size' : 100,'step_size' : 1e-3},verbose=True)

model.fit(X_train,y_train)


In [5]:
from data_utils import accuracy, confusion_matrix

preds = model.predict(X_test)



print(accuracy(preds, y_test))
print(confusion_matrix(preds, y_test))

0.9912159038372631
[[1.134e+03 1.000e+00]
 [1.800e+01 1.010e+03]]


In [6]:
from data_utils import accuracy, confusion_matrix
accs = {}
cms = {}
for k in [1,3,5,10,20,50,100,200]:
    print(f"k = {k}")
    X_train, X_test, y_train, y_test = get_train_test(k=k)
    model = LSQClassifier(solver='gauss')
    model.fit(X_train,y_train)

    preds = model.predict(X_test)
    acc = accuracy(preds, y_test)
    cm  = confusion_matrix(preds, y_test)
    print(accuracy(preds, y_test))
    print(confusion_matrix(preds, y_test))
    accs[k] = acc
    cms[k] = cm


0.6643550624133149
[[849. 286.]
 [440. 588.]]
0.9805825242718447
[[1125.   10.]
 [  32.  996.]]
0.9852057327785483
[[1128.    7.]
 [  25. 1003.]]


KeyboardInterrupt: 

In [ ]:
from LSQClassifier import LSQClassifier
from data_utils import get_train_test
import numpy as np

X_train, X_test, y_train, y_test = get_train_test(k=8)
X_train = (X_train - X_train.min()) / (X_train.max() - X_train.min())
def constant_step_size(iter,size=1e-1):
    return size # Fixed step size

def inverse_scaling(iter, eta0=1e-1, gamma=0.001):
    return eta0 / (1 + gamma * iter)

def exponential_decay(iter, eta0=1e-2, lam=0.01):
    return eta0 * np.exp(-lam * iter)

def step_decay(iter, eta0=5e-1, drop=0.5, epochs_drop=10):
    return eta0 * (drop ** (iter // epochs_drop))

model = LSQClassifier(solver='sgd',solverkwargs={'TOL' : 1e-3,'ITER_MAX' : 600,'batch_size' : 512,'step_size' : inverse_scaling},lam=0.5,verbose=True)

model.fit(X_train,y_train)



SGD, iter #0: loss = 5.3477e+01, gradnorm = 8.8168e+01
SGD, iter #1: loss = 6.3351e+00, gradnorm = 1.1441e+01
SGD, iter #2: loss = 4.3402e+00, gradnorm = 2.9928e+00
SGD, iter #3: loss = 4.1326e+00, gradnorm = 4.0678e-01
SGD, iter #4: loss = 4.1589e+00, gradnorm = 3.4543e-01
SGD, iter #5: loss = 4.1864e+00, gradnorm = 3.5687e-01
SGD, iter #6: loss = 4.2119e+00, gradnorm = 3.4017e-01
SGD, iter #7: loss = 4.2417e+00, gradnorm = 3.8968e-01
SGD, iter #8: loss = 4.2747e+00, gradnorm = 3.4386e-01
SGD, iter #9: loss = 4.3123e+00, gradnorm = 5.1016e-01
SGD, iter #10: loss = 4.3416e+00, gradnorm = 4.1992e-01
SGD, iter #11: loss = 4.3738e+00, gradnorm = 4.2325e-01
SGD, iter #12: loss = 4.4094e+00, gradnorm = 4.6863e-01
SGD, iter #13: loss = 4.4426e+00, gradnorm = 4.1405e-01
SGD, iter #14: loss = 4.4784e+00, gradnorm = 3.3493e-01
SGD, iter #15: loss = 4.5167e+00, gradnorm = 3.7928e-01
SGD, iter #16: loss = 4.5527e+00, gradnorm = 3.6018e-01
SGD, iter #17: loss = 4.5926e+00, gradnorm = 3.3053e-01
SG

In [4]:
from data_utils import accuracy, confusion_matrix

preds = model.predict(X_test)



print(accuracy(preds, y_test))
print(confusion_matrix(preds, y_test))

0.332871012482663
[[669. 466.]
 [977.  51.]]
